# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define "win01" do |win01|
    win01.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
    win01.vm.hostname = "win01"
    win01.vm.network "private_network", ip: "192.168.57.12"
    win01.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus =2
    end
  end

  config.vm.define "host_ansible" do |ans|
    ans.vm.box = "centos/7"
    ans.vm.hostname = "hostansible"
    ans.vm.network "private_network", ip: "192.168.57.10"
    ans.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
  end


  config.vm.define "linux01" do |db1|
    db1.vm.box = "centos/7"
    db1.vm.hostname = "linux01"
    db1.vm.network "private_network", ip: "192.168.57.11"
    db1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
  end

  config.vm.define "win02" do |win02|
    win02.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
    win02.vm.hostname = "win02"
    win02.vm.network "private_network", ip: "192.168.57.13"
    win02.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus =2
    end
  end




end
