---
# tasks file for linux


- name: Ensure nagios is installed
  yum:
    name: nagios
    state: present

- name: Ensure vim is installed
  yum:
    name: vim
    state: present

- name: Ensure git is installed
  yum:
    name: git
    state: present

...

